{{- if and .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slotting-optimization.databaseSecretName" . }}
  labels:
    {{- include "slotting-optimization.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.url | quote }}
{{- end }}