import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories follow the shared warehouse-systems documentation
 * layout: Overview, Operations, Development, Domain-Driven Design, API
 * Reference, Ecosystem and Architecture Decision Records. The ADR files live
 * in docs/adr/ and are served by the second docs plugin instance (id: 'adr'),
 * hence the plain links.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/introduction'},
      items: ['overview/architecture', 'overview/quickstart'],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {type: 'doc', id: 'operations/runbook'},
      items: [
        'operations/configuration',
        'operations/observability',
        'operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: ['development/testing'],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/ubiquitous-language'},
      items: [
        'ddd/use-cases',
        'ddd/subdomain-classification',
        {
          type: 'category',
          label: 'DDD artifacts (ddd-crew)',
          link: {type: 'doc', id: 'ddd/ddd-artifacts'},
          items: [
            'ddd/core-domain-chart',
            'ddd/bounded-context-canvas',
            'ddd/context-map',
            'ddd/aggregate-design-canvas',
            'ddd/domain-message-flow',
            'ddd/eventstorming',
            'ddd/class-diagram',
            'ddd/entity-relationship',
            'ddd/sequence-diagrams',
            'ddd/domain-events',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar, 'api-reference/events'],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: ['ecosystem/integration'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      items: [
        {
          type: 'link',
          label: 'ADR index',
          href: '/docs/adr',
        },
        {
          type: 'link',
          label: '0001 Bounded context',
          href: '/docs/adr/0001-slotting-optimization-bounded-context',
        },
        {
          type: 'link',
          label: '0002 SlotPlan and abc-velocity-v1',
          href: '/docs/adr/0002-slotplan-aggregate-and-abc-velocity-policy',
        },
        {
          type: 'link',
          label: '0003 Local copies and consumed contracts',
          href: '/docs/adr/0003-local-copies-and-consumed-contracts',
        },
        {
          type: 'link',
          label: '0004 CloudEvents envelope and type catalogue',
          href: '/docs/adr/0004-cloudevents-envelope-and-type-catalogue',
        },
      ],
    },
  ],
};

export default sidebars;
